### ISSUE TITLE
Merge documentation

### ISSUE THREAD

**Issue by laserlab** [ubsuny/MC-CP2P2024#12]
Please add links to your documentation / code in the main readme or merge the exiting information into it

**Comment by reshnashrestha** [comment]
@laserlab Isn't it already on the main readme? or I am not understanding what to do .

**Comment by laserlab** [comment]
the main readme is this file:
https://github.com/ubsuny/MC-CP2P2024/blob/main/README.md

**Comment by reshnashrestha** [comment]
Okay Thank you.

**Comment by reshnashrestha** [comment]
I have added links in the [README.md](https://github.com/ubsuny/MC-CP2P2024/blob/main/README.md). 
Please have your review @laserlab
