### ISSUE TITLE
Reference Qtip literature

### ISSUE THREAD

**Issue by laserlab** [ubsuny/MC-CP2P2024#8]
https://github.com/ubsuny/MC-CP2P2024/blob/83a61bdac90e9ea3554abca152ef1733cb591eda/data_type.md?plain=1#L9

A reference to Quito literature that documents this data type would be helpful

**Comment by reshnashrestha** [comment]
Yeah sure.  Thank you for noticing. I will add the reference. 
https://qutip.org/docs/latest/apidoc/classes.html

**Comment by reshnashrestha** [comment]
It's added.
https://github.com/ubsuny/MC-CP2P2024/blob/main/data_type.md
